blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, BlogListView

app_name = BlogConfig.name
urlpatterns = [
    path("list/", cache_page(60)(BlogListView.as_view()), name="list"),
    path("detail/<int:pk>/", cache_page(60)(BlogDetailView.as_view()), name="detail"),
    path("create/", BlogCreateView.as_view(), name="create"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('recipient/', include('recipient.urls', namespace='recipient')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', 'blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import MailingMessageListView, MailingMessageCreateView, MailingMessageDetailView, \
    MailingMessageUpdateView, MailingMessageDeleteView, MailingSettingsCreateView, MailingSettingsUpdateView, \
    MailingSettingsListView, MailingSettingsDetailView, MailingSettingsDeleteView, MailingMessageTemplateView

app_name = MailingConfig.name

urlpatterns = [
    path('', MailingMessageTemplateView.as_view(), name='home'),
    path('list/', MailingMessageListView.as_view(), name='list'),
    path('create/', MailingMessageCreateView.as_view(), name='create'),
    path('view/<int:pk>/', MailingMessageDetailView.as_view(), name='view'),
    path('update/<int:pk>/', MailingMessageUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MailingMessageDeleteView.as_view(), name='delete'),
    path('settings_list/', MailingSettingsListView.as_view(), name='settings_list'),
    path('settings_create/', MailingSettingsCreateView.as_view(), name='settings_create'),
    path('settings_view/<int:pk>/', MailingSettingsDetailView.as_view(), name='settings_view'),
    path('settings_edit/<int:pk>/', MailingSettingsUpdateView.as_view(), name='settings_edit'),
    path('settings_delete/<int:pk>/', MailingSettingsDeleteView.as_view(), name='settings_delete'),
]

mailing/models.py
from django.db import models

from recipient.models import Recipient
from users.models import User

NULLABLE = {'null': True, 'blank': True}
FREQUENCY_CHOICES = [('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц'), ]
STATUS_OF_NEWSLETTER = [("Create", 'Создана'), ("Started", 'Отправлено'), ("Done", 'Завершена'), ]
LOGS_STATUS_CHOICES = [('success', 'успешно'), ('fail', 'неуспешно'), ]


class MailingMessage(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Контент')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, verbose_name='Владелец')

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.title


class MailingSettings(models.Model):
    first_datetime = models.DateTimeField(auto_now_add=True, verbose_name='Начало рассылки')
    end_time = models.DateTimeField(verbose_name='Конец рассылки', **NULLABLE)
    sending = models.CharField(max_length=50, choices=FREQUENCY_CHOICES, verbose_name='Период рассылки')
    message = models.ForeignKey(MailingMessage, on_delete=models.CASCADE, verbose_name='Сообщения')
    setting_status = models.CharField(max_length=50, choices=STATUS_OF_NEWSLETTER, verbose_name='Статус рассылки',
                                      default='Create')
    recipients = models.ManyToManyField(Recipient, verbose_name='Получатели')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, verbose_name='Владелец')

    class Meta:
        verbose_name = 'Настройка рассылки'
        verbose_name_plural = 'Настройки рассылки'
        permissions = [
            ('change_mailingsettings_setting_status', 'Can change mailingsettings setting_status')
        ]

    def __str__(self):
        return f'{self.message} отправляется каждый {self.sending} с {self.first_datetime}'


class MailingStatus(models.Model):
    last_datetime = models.DateTimeField(auto_now_add=True, verbose_name='last_datetime')
    status = models.CharField(max_length=50, choices=LOGS_STATUS_CHOICES, default='', verbose_name='статус попытки')
    mailing_response = models.TextField(verbose_name='mailing_response')
    mailing_list = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='рассылка')
    recipient = models.ForeignKey(Recipient, on_delete=models.CASCADE, verbose_name='клиент рассылки', **NULLABLE)

    class Meta:
        verbose_name = 'Статус отправки'
        verbose_name_plural = 'Статусы отправки'

    def __str__(self):
        return f'{self.status} отправлялось {self.last_datetime}, ответ сервера: {self.mailing_response}'

mailing/forms.py
from django import forms

from common.views import StyleFormMixin
from mailing.models import MailingSettings, MailingMessage
from recipient.models import Recipient


class MailingSettingsForm(StyleFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        user = self.request.user
        super().__init__(*args, **kwargs)
        self.fields['recipients'].queryset = Recipient.objects.filter(owner=user)
        self.fields['message'].queryset = MailingMessage.objects.filter(owner=user)

    class Meta:
        model = MailingSettings
        fields = ('sending', 'recipients', 'message', 'end_time',)


class MailingMessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingMessage
        fields = ('title', 'content',)


class MailingModeratorForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('setting_status',)

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView, TemplateView

from mailing.forms import MailingMessageForm, MailingSettingsForm, MailingModeratorForm
from mailing.models import MailingMessage, MailingSettings
from mailing.services import get_blog_from_cache
from recipient.models import Recipient


class MailingMessageTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'mailing/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['blogs'] = get_blog_from_cache()
        mailing_settings = MailingSettings.objects.all()
        context_data['mailing_settings'] = len(mailing_settings)
        active_mailings = MailingSettings.objects.filter(setting_status='Started')
        context_data['active_mailings'] = len(active_mailings)
        recipients = Recipient.objects.all()
        context_data['recipient'] = len(recipients)
        return context_data


class MailingMessageCreateView(LoginRequiredMixin, CreateView):
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy('mailing:list')

    def form_valid(self, form):
        message = form.save()
        message.owner = self.request.user
        message.save()
        return super().form_valid(form)


class MailingMessageUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingMessage
    form_class = MailingMessageForm
    success_url = reverse_lazy('mailing:list')


class MailingMessageDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingMessage
    success_url = reverse_lazy('mailing:list')


class MailingMessageListView(LoginRequiredMixin, ListView):
    model = MailingMessage


class MailingMessageDetailView(LoginRequiredMixin, DetailView):
    model = MailingMessage


class MailingSettingsCreateView(LoginRequiredMixin, CreateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing:settings_list')

    def form_valid(self, form):
        settings = form.save()
        settings.owner = self.request.user
        settings.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class MailingSettingsUpdateView(LoginRequiredMixin, UpdateView):
    model = MailingSettings
    form_class = MailingSettingsForm
    success_url = reverse_lazy('mailing:settings_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return MailingSettingsForm
        if user.has_perm('mailing.change_mailingsettings_setting_status'):
            return MailingModeratorForm
        return PermissionDenied

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({'request': self.request})
        return kwargs


class MailingSettingsListView(LoginRequiredMixin, ListView):
    model = MailingSettings


class MailingSettingsDetailView(LoginRequiredMixin, DetailView):
    model = MailingSettings


class MailingSettingsDeleteView(LoginRequiredMixin, DeleteView):
    model = MailingSettings
    success_url = reverse_lazy('mailing:settings_list')

mailing/templates/mailing/home.html
{% extends 'recipient/base.html' %}
{% block content %}
{% load my_tags %}
<div class="row mb-5">
<div class="col-md-4">
    <div class="p-5 border">
        <h1>
            <strong>{{ mailing_settings }}</strong>
        </h1>
        <h1>
            Количество рассылок всего
        </h1>
    </div>
</div>
<div class="col-md-4">
    <div class="p-5 border">
        <h1>
            <strong>{{ active_mailings }}</strong>
        </h1>
        <h1>
            Количество активных рассылок
        </h1>
    </div>
</div>
<div class="col-md-4">
    <div class="p-5 border">
        <h1>
            <strong>{{ recipient }}</strong>
        </h1>
        <h1>
            Количество уникальных клиентов
        </h1>
    </div>
</div>
</div>
<div class="row row-cols-1 row-cols-md-3 text-center">
    {% for object in blogs %}
    <div class="col">
        <div class="card h-100">
            <div class="card-header py-3">
                <h4 class="my-0 fw-normal">{{ object.title }}</h4>
            </div>
            <img class="card-img-top mb-3 p-2" src="{{ object.image | media_filter }}" alt="">
            <div class="card-body">
                <p class="card-title pricing-card-title">{{ object.body|truncatechars:50 }}</p>
                <a class="btn btn-primary" href="{% url 'blog:detail' object.pk %}"
                   role="button">Просмотреть</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

mailing/templates/mailing/mailingmessage_confirm_delete.html
{% extends 'recipient/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку {{ object.title }}?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'mailing:list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingmessage_detail.html
{% extends 'recipient/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-9">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <h5>{{ object.content }}</h5>
                    <p>{{ object.recipients }}</p>
                    {% if user == object.owner or user.is_superuser %}
                    <a class="btn btn-primary" href="{% url 'mailing:edit' object.pk %}" role="button">Изменить</a>
                    <a class="btn btn-primary" href="{% url 'mailing:delete' object.pk %}" role="button">Удалить</a>
                    {% endif %}
                    <a class="btn btn-primary" href="{% url 'mailing:list' %}" role="button">Назад</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingmessage_form.html
{% extends 'recipient/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">
                        {% if object %}
                            Изменить сообщение
                        {% else %}
                            Добавить сообщение
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingmessage_list.html
{% extends 'recipient/base.html' %}

{% block content %}
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
      <h1 class="display-4 fw-normal text-body-emphasis">Все рассылки</h1>
    </div>
    </header>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
      {% for mail in object_list %}
        {% if user == mail.owner or user.is_superuser or perms.mailing.view_mailingmessage %}
        <div class="col">
          <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
              <h2 class="my-0 fw-normal">{{ mail.title }}</h2>
            </div>
            <div class="card-body">
              <p class="card-title pricing-card-title">{{ mail.content | slice:":100" }}</p>
              <a class="btn btn-primary" href="{% url 'mailing:view' mail.pk %}" role="button">Просмотреть</a>
            </div>
          </div>
        </div>
       {% endif %}
      {% endfor %}
    </div>

{% endblock %}

mailing/templates/mailing/mailingsettings_confirm_delete.html
{% extends 'recipient/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку {{ object.title }}?</p>
                        <button type="submit" class="btn btn-success">Удалить</button>
                        <a class="btn btn-primary" href="{% url 'mailing:settings_list' %}" role="button">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/mailingsettings_detail.html
{% extends 'recipient/base.html' %}
{% block content %}
<div class="container">
  <div class="row text-center">
    <div class="col-9">
      <div class="card mb-4 box-shadow">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
        </div>
        <div class="card-body">
          <h5>{{ object.content }}</h5>
          {% for item in object.recipients.all %}
          <p>{{ item }}</p>
          {% endfor %}
          {% if user == object.owner or user.is_superuser or perms.mailing.change_mailingsettings_setting_status %}
          <a class="btn btn-primary" href="{% url 'mailing:settings_edit' object.pk %}"
             role="button">Изменить</a>
          {% endif %}
          <a class="btn btn-primary" href="{% url 'mailing:settings_list' %}" role="button">Назад</a>
          {% if user == object.owner or user.is_superuser %}
          <a class="btn btn-primary" href="{% url 'mailing:settings_delete' object.pk %}" role="button">Удалить</a>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingsettings_form.html
{% extends 'recipient/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card">
                    <div class="card-body">
                        {{ form.as_p }}
                    </div>
                    <button type="submit" class="btn btn-primary mt-3">
                        {% if object %}
                            Изменить настройки рассылки
                        {% else %}
                            Добавить рассылку
                        {% endif %}
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/mailingsettings_list.html
{% extends 'recipient/base.html' %}

{% block content %}
<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal text-body-emphasis">Запланированные рассылки</h1>
    <h3>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'mailing:settings_create' %}">Запланировать
            рассылку</a>
    </h3>
</div>
</header>

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    {% for object in object_list %}
    {% if user == object.owner or user.is_superuser or perms.mailing.change_mailingsettings_setting_status %}
    <div class="col">
        <div class="card mb-4 rounded-3 shadow-sm">
            <div class="card-header py-3">
                <h2 class="my-0 fw-normal">Создана: {{ object.first_datetime }}</h2>
            </div>
            <div class="card-body">
                {% for item in object.recipients.all %}
                <p class="card-title pricing-card-title">Для: {{ item }}</p>
                {% endfor %}
                <p class="card-title pricing-card-title">Периодичность: {{object.sending}}</p>
                <p class="card-title pricing-card-title">Завершится: {{ object.end_time }}</p>
                <a class="btn btn-primary" href="{% url 'mailing:settings_view' object.pk %}"
                   role="button">Просмотреть</a>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>

{% endblock %}