blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, BlogListView

app_name = BlogConfig.name
urlpatterns = [
    path("list/", cache_page(60)(BlogListView.as_view()), name="list"),
    path("detail/<int:pk>/", cache_page(60)(BlogDetailView.as_view()), name="detail"),
    path("create/", BlogCreateView.as_view(), name="create"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('recipient/', include('recipient.urls', namespace='recipient')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', 'blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipient/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from recipient.apps import RecepientConfig
from recipient.views import (RecipientListView, RecipientCreateView, RecipientDeleteView,
                             RecipientDetailView, RecipientUpdateView)

app_name = RecepientConfig.name

urlpatterns = [
    path('', RecipientListView.as_view(), name='list'),
    path('create/', RecipientCreateView.as_view(), name='create'),
    path('view/<int:pk>/', cache_page(60)(RecipientDetailView.as_view()), name='view'),
    path('update/<int:pk>/', RecipientUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', RecipientDeleteView.as_view(), name='delete'),
]

recipient/models.py
from django.db import models

from users.models import User

NULLABLE = {'null': True, 'blank': True}


class Recipient(models.Model):
    email = models.EmailField(verbose_name='Почта', unique=True)
    name = models.CharField(max_length=100, verbose_name='Имя')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, verbose_name='Владелец')

    def __str__(self):
        return f'{self.email} - {self.name}'

    class Meta:
        verbose_name = 'Получатель'
        verbose_name_plural = 'Получатели'

recipient/forms.py
from django import forms

from common.views import StyleFormMixin
from recipient.models import Recipient


class RecipientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Recipient
        fields = ('email', 'name', 'description',)

recipient/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from recipient.forms import RecipientForm
from recipient.models import Recipient


# Create your views here.
class RecipientListView(LoginRequiredMixin, ListView):
    model = Recipient


class RecipientDetailView(LoginRequiredMixin, DetailView):
    model = Recipient


class RecipientCreateView(LoginRequiredMixin, CreateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy('recipient:list')

    def form_valid(self, form):
        recipient = form.save()
        recipient.owner = self.request.user
        recipient.save()
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipient
    form_class = RecipientForm

    def get_success_url(self):
        return reverse_lazy('recipient:view', kwargs={'pk': self.get_object().id})


class RecipientDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipient
    success_url = reverse_lazy('recipient:list')

recipient/templates/recipient/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>
      <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Blog Template · Bootstrap v5.3</title>



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair&#43;Display:700,900&amp;display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
  </head>
  <body>
  {% include 'includes/inc_main_menu.html'%}
  {% block content %}

  {% endblock %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

  </body>
</html>

recipient/templates/recipient/recipient_confirm_delete.html
{% extends 'recipient/base.html' %}
{% block content %}
<div class="container px-3 py-3 pt-md-5 pb-md-4">
<div class="col-12 mb-5 pt-md-5">
    <div class="row">
        <div class="col-lg-6 text-center">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить получателя? "{{object.email}}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'recipient:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    </div>
{% endblock %}

recipient/templates/recipient/recipient_detail.html
{% extends 'recipient/base.html' %}
{% block content %}
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }} ({{ object.email }})</h4>
                </div>
                <div class="card-body">
                    <div class="card-footer text-centr">
                        Комментарии: {{ object.description }}
                    </div>
                </div>
                {% if user == object.owner or user.is_superuser %}
                <a href="{% url 'recipient:edit' object.pk %}" class="btn btn-warning">Изменить</a>
                <a href="{% url 'recipient:delete' object.pk %}" class="btn btn-danger">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

recipient/templates/recipient/recipient_form.html
{% extends 'recipient/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

recipient/templates/recipient/recipient_list.html
{% extends 'recipient/base.html' %}
{% block content %}
<div class="row text-center">
    {% for recipient in object_list %}
    {% if user == recipient.owner or user.is_superuser or perms.mailing.change_mailingsettings_setting_status %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ recipient.email }}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li>- {{ recipient.description|slice:100 }}</li>
                    <li>- {{ recipient.name }}</li>
                </ul>
                <a href="{% url 'recipient:view' recipient.pk %}" type="button"
                   class="btn btn-lg btn-block btn-outline-primary">Подробнее</a>
            </div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}