blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, BlogListView

app_name = BlogConfig.name
urlpatterns = [
    path("list/", cache_page(60)(BlogListView.as_view()), name="list"),
    path("detail/<int:pk>/", cache_page(60)(BlogDetailView.as_view()), name="detail"),
    path("create/", BlogCreateView.as_view(), name="create"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('recipient/', include('recipient.urls', namespace='recipient')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', 'blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from users.models import User

NULLABLE = {"null": True, "blank": True}


class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name="Заголовок")
    body = models.TextField(verbose_name="Содержимое")
    image = models.ImageField(upload_to="blog/", verbose_name="Изображение", **NULLABLE)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=True, verbose_name="Признак публикации")
    view_count = models.IntegerField(default=0, verbose_name="Количество просмотров")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, verbose_name="Владелец")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "блог"
        verbose_name_plural = "блоги"

blog/forms.py
from django import forms

from blog.models import Blog
from common.views import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'body', 'image', 'is_published')

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, DetailView, ListView

from blog.forms import BlogForm
from blog.models import Blog


class BlogListView(LoginRequiredMixin, ListView):
    model = Blog


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        post = form.save()
        post.owner = self.request.user
        post.save()
        return super().form_valid(form)


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm

    def get_success_url(self):
        return reverse_lazy('blog:detail', kwargs={'pk': self.get_object().id})

blog/templates/blog/blog_confirm_delete.html
{% extends 'recipient/base.html' %}
{% block content %}
<div class="container px-3 py-3 pt-md-5 pb-md-4">
<div class="col-12 mb-5 pt-md-5">
    <div class="row">
        <div class="col-lg-6 text-center">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить отзыв "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'recipient/base.html' %}
{% block content %}
{% load my_tags %}
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    {% if object.image %}
                    <img class="card-img-top" src="{{ object.image | media_filter }}">
                    {% endif %}
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.body }}</li>
                    </ul>
                    <div class="card-footer text-centr">
                        Просмотры: {{ object.view_count }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'recipient/base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'recipient/base.html' %}
{% load my_tags %}
{% block content %}
<div class="container px-3 py-3 pt-md-5 pb-md-4">
    <div class="col-12 mb-5 pt-md-5">
        {% if user.is_superuser or perms.blog.add_blog %}
        <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Добавить отзыв</a>
        {% endif %}
    </div>
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-6">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body">
                    <img class="card-img-top" src="{{ object.image | media_filter }}">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.body|slice:100 }}</li>
                    </ul>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blog:detail' object.pk %}" type="button"
                               class="btn btn-lg btn-block btn-outline-primary">Подробнее</a>
                            {% if user.is_superuser or perms.blog.change_blog %}
                            <a href="{% url 'blog:update' object.pk %}" type="button"
                               class="btn btn-lg btn-block btn-outline-primary">Изменить</a>
                            {% endif %}
                            {% if user.is_superuser or perms.blog.delete_blog %}
                            <a href="{% url 'blog:delete' object.pk %}" type="button"
                               class="btn btn-lg btn-block btn-outline-primary">Удалить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}