blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogUpdateView, BlogDeleteView, BlogDetailView, BlogListView

app_name = BlogConfig.name
urlpatterns = [
    path("list/", cache_page(60)(BlogListView.as_view()), name="list"),
    path("detail/<int:pk>/", cache_page(60)(BlogDetailView.as_view()), name="detail"),
    path("create/", BlogCreateView.as_view(), name="create"),
    path("update/<int:pk>/", BlogUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", BlogDeleteView.as_view(), name="delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('recipient/', include('recipient.urls', namespace='recipient')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', 'blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import MailingMessageListView, MailingMessageCreateView, MailingMessageDetailView, \
    MailingMessageUpdateView, MailingMessageDeleteView, MailingSettingsCreateView, MailingSettingsUpdateView, \
    MailingSettingsListView, MailingSettingsDetailView, MailingSettingsDeleteView, MailingMessageTemplateView

app_name = MailingConfig.name

urlpatterns = [
    path('', MailingMessageTemplateView.as_view(), name='home'),
    path('list/', MailingMessageListView.as_view(), name='list'),
    path('create/', MailingMessageCreateView.as_view(), name='create'),
    path('view/<int:pk>/', MailingMessageDetailView.as_view(), name='view'),
    path('update/<int:pk>/', MailingMessageUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', MailingMessageDeleteView.as_view(), name='delete'),
    path('settings_list/', MailingSettingsListView.as_view(), name='settings_list'),
    path('settings_create/', MailingSettingsCreateView.as_view(), name='settings_create'),
    path('settings_view/<int:pk>/', MailingSettingsDetailView.as_view(), name='settings_view'),
    path('settings_edit/<int:pk>/', MailingSettingsUpdateView.as_view(), name='settings_edit'),
    path('settings_delete/<int:pk>/', MailingSettingsDeleteView.as_view(), name='settings_delete'),
]

recipient/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from recipient.apps import RecepientConfig
from recipient.views import (RecipientListView, RecipientCreateView, RecipientDeleteView,
                             RecipientDetailView, RecipientUpdateView)

app_name = RecepientConfig.name

urlpatterns = [
    path('', RecipientListView.as_view(), name='list'),
    path('create/', RecipientCreateView.as_view(), name='create'),
    path('view/<int:pk>/', cache_page(60)(RecipientDetailView.as_view()), name='view'),
    path('update/<int:pk>/', RecipientUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', RecipientDeleteView.as_view(), name='delete'),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, ProfileView, reset_password, UserLoginView

app_name = UsersConfig.name

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("reset_password/", reset_password, name="reset_password"),
]

blog/models.py
from django.db import models

from users.models import User

NULLABLE = {"null": True, "blank": True}


class Blog(models.Model):
    title = models.CharField(max_length=250, verbose_name="Заголовок")
    body = models.TextField(verbose_name="Содержимое")
    image = models.ImageField(upload_to="blog/", verbose_name="Изображение", **NULLABLE)
    create_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    is_published = models.BooleanField(default=True, verbose_name="Признак публикации")
    view_count = models.IntegerField(default=0, verbose_name="Количество просмотров")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, verbose_name="Владелец")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "блог"
        verbose_name_plural = "блоги"

recipient/models.py
from django.db import models

from users.models import User

NULLABLE = {'null': True, 'blank': True}


class Recipient(models.Model):
    email = models.EmailField(verbose_name='Почта', unique=True)
    name = models.CharField(max_length=100, verbose_name='Имя')
    description = models.TextField(verbose_name='Описание', **NULLABLE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, **NULLABLE, verbose_name='Владелец')

    def __str__(self):
        return f'{self.email} - {self.name}'

    class Meta:
        verbose_name = 'Получатель'
        verbose_name_plural = 'Получатели'

recipient/forms.py
from django import forms

from common.views import StyleFormMixin
from recipient.models import Recipient


class RecipientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Recipient
        fields = ('email', 'name', 'description',)

recipient/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from recipient.forms import RecipientForm
from recipient.models import Recipient


# Create your views here.
class RecipientListView(LoginRequiredMixin, ListView):
    model = Recipient


class RecipientDetailView(LoginRequiredMixin, DetailView):
    model = Recipient


class RecipientCreateView(LoginRequiredMixin, CreateView):
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy('recipient:list')

    def form_valid(self, form):
        recipient = form.save()
        recipient.owner = self.request.user
        recipient.save()
        return super().form_valid(form)


class RecipientUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipient
    form_class = RecipientForm

    def get_success_url(self):
        return reverse_lazy('recipient:view', kwargs={'pk': self.get_object().id})


class RecipientDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipient
    success_url = reverse_lazy('recipient:list')

recipient/templates/includes/inc_main_menu.html
 <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <nav class="nav nav-underline justify-content-between">
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'mailing:home' %}">Главная страница</a>
        {% if user.is_authenticated %}
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'recipient:list' %}">Все получатели</a>
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'recipient:create' %}">Добавить получателя</a>
        {% if perms.blog.add_blog %}
         <a class="nav-item nav-link link-body-emphasis" href="{% url 'blog:create' %}">Добавить блог</a>
        {% endif %}
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'mailing:list' %}">Все сообщения</a>
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'mailing:settings_list' %}">Планирование
            рассылок</a>
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'mailing:create' %}">Создание сообщения</a>
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'blog:list' %}">Посты</a>
        {% endif %}
        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>
        <form action="{% url 'users:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-outline-primary"> Выйти</button>
        </form>
        {% else %}
        <a type="button" class="btn btn-outline-primary me-2" href="{% url 'users:login' %}">Войти</a>
        <a type="button" class="btn btn-primary" href="{% url 'users:register' %}">Зарегистрироваться</a>
        {% endif %}
        {% if user.is_superuser %}
        <a class="nav-item nav-link link-body-emphasis" href="{% url 'admin:index' %}">Админ-панель</a>
        {% endif %}
    </nav>
</div>